import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.saucedemo.com/');
  await page.waitForTimeout(3000);
  await page.locator('[data-test="username"]').click();
  await page.locator('[data-test="username"]').fill('standard_user');
  await page.locator('[data-test="password"]').click();
  await page.locator('[data-test="password"]').fill('secret_sauce');
  await page.locator('[data-test="login-button"]').click();
  await page.waitForTimeout(3000);
  await page.locator('[data-test="add-to-cart-sauce-labs-backpack"]').click();
  await page.locator('[data-test="shopping-cart-link"]').click();
  await page.locator('[data-test="checkout"]').click();
  await page.locator('[data-test="firstName"]').click();
  await page.locator('[data-test="firstName"]').fill('Rohit Sasanala');
  await page.locator('[data-test="lastName"]').click();
  await page.locator('[data-test="firstName"]').click();
  await page.locator('[data-test="firstName"]').fill('Rohit');
  await page.locator('[data-test="lastName"]').click();
  await page.locator('[data-test="lastName"]').fill('Sasanala');
  await page.locator('[data-test="postalCode"]').click();
  await page.locator('[data-test="postalCode"]').fill('507101');
  await page.waitForTimeout(3000);
  await page.locator('[data-test="checkout-info-container"]').click();
  await page.locator('[data-test="continue"]').click();
  await page.locator('[data-test="finish"]').click();
  const downloadPromise = page.waitForEvent('download');
  await page.locator('[data-test="generate-pdf-order"]').click();
  const download = await downloadPromise;
  await page.locator('[data-test="back-to-products"]').click();
});